Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -52,7 +52,14 @@ jobs:
 
     - name: Create DB
       run: |
-        mysql -u root -p"1998@Pupss" -e "CREATE DATABASE assignment1"
+        run: |
+          if ! sudo mysql -u root -p1998@Pupss -e "CREATE DATABASE assignment1"; then
+          echo "Failed to create the database"
+          exit 1
+          fi
+
+    - name: Check MySQL Error Log
+      run: sudo cat /var/log/mysql/error.log
 
     - name: Run tests
       run: npm test
