Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,7 +10,6 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     services:
@@ -31,29 +30,29 @@ jobs:
         node-version: [16.x, 18.x]
 
     steps:
-    - uses: actions/checkout@v2
-    - name: Clear npm cache
-      run: npm cache clean --force
-    - name: Set npm cache path
-      run: npm config set cache ~/.npm
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v2
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-        cache-dependency-path: ./server/package-lock.json
-    - run: npm install
-    - run: npm run build --if-present
-    - name: Start Node.js Server
-      run: npm start &
-    - name: Wait for Node.js Server to Start
-      run: sleep 10 # Adjust as needed
-    - name: Test /healthz
-      run: |
-        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/healthz)
-        if [ "$response" = "200" ]; then
-          echo "Health check passed"
-        else
-          echo "Health check failed"
-          exit 1
-        fi
+      - uses: actions/checkout@v2
+      - name: Clear npm cache
+        run: npm cache clean --force
+      - name: Set npm cache path
+        run: npm config set cache ~/.npm
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: 'npm'
+          cache-dependency-path: ./server/package-lock.json
+      - run: npm install
+      - run: npm run build --if-present
+      - name: Start Node.js Server
+        run: npm start &
+      - name: Wait for Node.js Server to Start
+        run: sleep 10 # Adjust as needed
+      - name: Test /healthz
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/healthz)
+          if [ "$response" = "200" ]; then
+            echo "Health check passed"
+          else
+            echo "Health check failed"
+            exit 1
+          fi
